-- =====================================================
-- RETAIL SALES ANALYSIS USING SQL
-- =====================================================
-- Author: Prapti Khandelwal
-- Database: retail_sales_db
-- Description:
-- This project analyzes retail sales data to generate
-- business insights using SQL.
-- =====================================================

USE retail_sales_db;

-- =====================================================
-- DATA EXPLORATION
-- =====================================================

-- -----------------------------------------------------
-- Question 1: How many records are present in the dataset?
-- -----------------------------------------------------

SELECT COUNT(*) AS total_records
FROM retail_sales;

-- -----------------------------------------------------
-- Question 2: Preview the dataset.
-- -----------------------------------------------------

SELECT *
FROM retail_sales
LIMIT 10;

-- -----------------------------------------------------
-- Question 3: Check for missing values in the dataset.
-- -----------------------------------------------------

SELECT *
FROM retail_sales
WHERE `Transaction ID` IS NULL
   OR `Date` IS NULL
   OR `Customer ID` IS NULL
   OR Gender IS NULL
   OR Age IS NULL
   OR `Product Category` IS NULL
   OR Quantity IS NULL
   OR `Price per Unit` IS NULL
   OR `Total Amount` IS NULL;
   
-- =====================================================
-- SALES ANALYSIS
-- =====================================================

-- -----------------------------------------------------
-- Question 4: Display all unique product categories.
-- -----------------------------------------------------

SELECT DISTINCT `Product Category`
FROM retail_sales;

-- -----------------------------------------------------
-- Question 5: Which product category generated the highest revenue?
-- -----------------------------------------------------

SELECT
    `Product Category`,
    SUM(`Total Amount`) AS Total_Revenue
FROM retail_sales
GROUP BY `Product Category`
ORDER BY Total_Revenue DESC;

-- -----------------------------------------------------
-- Question 6: Which product category sold the highest quantity?
-- -----------------------------------------------------

SELECT
    `Product Category`,
    SUM(Quantity) AS Total_Quantity_Sold
FROM retail_sales
GROUP BY `Product Category`
ORDER BY Total_Quantity_Sold DESC;

-- =====================================================
-- CUSTOMER ANALYSIS
-- =====================================================

-- -----------------------------------------------------
-- Question 7: How much revenue was generated by each gender?
-- -----------------------------------------------------

SELECT
    Gender,
    SUM(`Total Amount`) AS Total_Revenue
FROM retail_sales
GROUP BY Gender
ORDER BY Total_Revenue DESC;

-- -----------------------------------------------------
-- Question 8: Which age group generates the highest revenue?
-- -----------------------------------------------------

SELECT
    CASE
        WHEN Age < 20 THEN 'Below 20'
        WHEN Age BETWEEN 20 AND 29 THEN '20-29'
        WHEN Age BETWEEN 30 AND 39 THEN '30-39'
        WHEN Age BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END AS Age_Group,
    SUM(`Total Amount`) AS Total_Revenue
FROM retail_sales
GROUP BY Age_Group
ORDER BY Total_Revenue DESC;

-- -----------------------------------------------------
-- Question 9: What is the average amount spent per transaction?
-- -----------------------------------------------------

SELECT
    ROUND(AVG(`Total Amount`), 2) AS Average_Transaction_Value
FROM retail_sales;

-- -----------------------------------------------------
-- Question 10: Which are the Top 10 highest-value transactions?
-- -----------------------------------------------------

SELECT
    `Transaction ID`,
    `Customer ID`,
    `Product Category`,
    Quantity,
    `Total Amount`
FROM retail_sales
ORDER BY `Total Amount` DESC
LIMIT 10;

-- =====================================================
-- TIME-BASED ANALYSIS
-- =====================================================

-- -----------------------------------------------------
-- Question 11: Which month generated the highest revenue?
-- -----------------------------------------------------

SELECT
    MONTHNAME(`Date`) AS Month,
    SUM(`Total Amount`) AS Total_Revenue
FROM retail_sales
GROUP BY MONTH(`Date`), MONTHNAME(`Date`)
ORDER BY Total_Revenue DESC;

-- -----------------------------------------------------
-- Question 12: What is the daily sales trend?
-- -----------------------------------------------------

SELECT
    `Date`,
    SUM(`Total Amount`) AS Daily_Revenue
FROM retail_sales
GROUP BY `Date`
ORDER BY `Date`;

-- =====================================================
-- PRODUCT ANALYSIS
-- =====================================================

-- -----------------------------------------------------
-- Question 13: Average quantity purchased by product category.
-- -----------------------------------------------------

SELECT
    `Product Category`,
    ROUND(AVG(Quantity),2) AS Average_Quantity
FROM retail_sales
GROUP BY `Product Category`
ORDER BY Average_Quantity DESC;

-- -----------------------------------------------------
-- Question 14: Which product category has the highest average transaction value?
-- -----------------------------------------------------

SELECT
    `Product Category`,
    ROUND(AVG(`Total Amount`),2) AS Average_Transaction
FROM retail_sales
GROUP BY `Product Category`
ORDER BY Average_Transaction DESC;

-- -----------------------------------------------------
-- Question 15: Find customers whose transactions are above the average transaction amount.
-- -----------------------------------------------------

SELECT
    `Customer ID`,
    `Total Amount`
FROM retail_sales
WHERE `Total Amount` >
(
    SELECT AVG(`Total Amount`)
    FROM retail_sales
)
ORDER BY `Total Amount` DESC
limit 10;

-- =====================================================
-- ADVANCED BUSINESS ANALYSIS
-- =====================================================

-- -----------------------------------------------------
-- Question 16: Which customer made the highest number of purchases?
-- -----------------------------------------------------

SELECT
    `Customer ID`,
    COUNT(*) AS Total_Orders
FROM retail_sales
GROUP BY `Customer ID`
ORDER BY Total_Orders DESC
LIMIT 10;

-- -----------------------------------------------------
-- Question 17: Which age group places the most orders?
-- -----------------------------------------------------

SELECT
    CASE
        WHEN Age < 20 THEN 'Below 20'
        WHEN Age BETWEEN 20 AND 29 THEN '20-29'
        WHEN Age BETWEEN 30 AND 39 THEN '30-39'
        WHEN Age BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END AS Age_Group,
    COUNT(*) AS Total_Orders
FROM retail_sales
GROUP BY Age_Group
ORDER BY Total_Orders DESC;

-- -----------------------------------------------------
-- Question 18: Find the highest and lowest transaction amount.
-- -----------------------------------------------------

SELECT
    MAX(`Total Amount`) AS Highest_Sale,
    MIN(`Total Amount`) AS Lowest_Sale
FROM retail_sales;

-- -----------------------------------------------------
-- Question 19: Number of transactions by product category.
-- -----------------------------------------------------

SELECT
    `Product Category`,
    COUNT(*) AS Total_Transactions
FROM retail_sales
GROUP BY `Product Category`
ORDER BY Total_Transactions DESC;

-- -----------------------------------------------------
-- Question 20: Find transactions where quantity sold is above average.
-- -----------------------------------------------------

SELECT
    `Transaction ID`,
    `Product Category`,
    Quantity,
    `Total Amount`
FROM retail_sales
WHERE Quantity >
(
    SELECT AVG(Quantity)
    FROM retail_sales
)
ORDER BY Quantity DESC;